# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  - group: Docker-Variables

stages:
   - stage: Build
     displayName: Build
     jobs:
       - job: Build
         displayName: Build
         pool:
            vmImage: ubuntu-latest
         steps:
          - checkout: self
            clean: true
            fetchDepth: 1
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: x64
              jdkSourceOption: PreInstalled
          - script: | 
             echo 'Maven version:'
              mvn -version
            displayName: Show maven Version
          
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
          - task: CopyFiles@2
            inputs:
              Contents: 'target/**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/target'

              
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerLink'
              repository: 'anand2993/webapp'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
   - stage: InstallDocker
     jobs:
      - job: InstallDocker
        displayName: 'Install Docker Engine'
        steps:
         - script: |
            
            sudo apt-get update
      
            # Install packages to allow apt to use a repository over HTTPS
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      
            # Add Docker’s official GPG key
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      
             # Add the Docker APT repository
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      
            # Update the apt package index again
            sudo apt-get update
      
            # Install Docker
            sudo apt-get install -y docker-ce
      
            # Start Docker service
            sudo systemctl start docker
      
            # Enable Docker service to start on boot
            sudo systemctl enable docker
      
           
           displayName: 'Install Docker Engine'

   - stage: Deploy
     displayName: Deploy
     jobs:
      - job: Run
        steps:
         - script: |
            
              echo "Logging in to Docker registry"
              sudo docker login -u $(dockerUsername) -p $(dockerPassword)
              echo "Login Successful"

              #Pulling the Docker image
              echo "Pulling Docker image"
              sudo docker pull $(dockerImageName):104

              #Running the Docker Image

              echo "Running Docker container"
              sudo docker run -d --name web-app $(dockerImageName):104

              #Checking Container status
              sudo docker ps
      