apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: <your-java-app-image>
        ports:
        - containerPort: 8080
        env:
        - name: JDBC_URL
          value: "jdbc:mysql://my-mysql.my-app.svc.cluster.local:3306/$(MYSQL_DATABASE)"
        - name: JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
