apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: my-app
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # base64 encoded value of 'rootpassword'
  mysql-user: bXl1c2Vy                 # base64 encoded value of 'myuser'
  mysql-password: bXlwYXNzd29yZA==      # base64 encoded value of 'mypassword'
  mysql-database: bXlkYXRhYmFzZQ==      # base64 encoded value of 'mydatabase'
